### ISSUE TITLE
Additional reflection questions below pie charts

### ISSUE THREAD

**Issue by jayperryworks** [E2A/e2a-cip#80]
### Request:
We should include reflection questions under the two domain pie charts (the ones that divide the proportion of the budget and activities by domain). The young people had no way to really reflect on what the pie charts should ideally look like. We would, of course, supply these questions.

### Feature Description:
Additional text will need to be added below each pie chart following similar design to the text currently below each of the country indicators.

### Note:
This will likely require additional design discussions given the page is already increasingly saturated with text and adding more may decrease design efficacy.

- [x] Get text from E2A
- [ ] Put text in place

**Comment by sschafft** [comment]
@ewilliams3794 - just flagging we need some text for this.
