### ISSUE TITLE
Adjustment to Iconography

### ISSUE THREAD

**Issue by jayperryworks** [E2A/e2a-cip#83]
### Request:
There needs to be better correspondence between the icons and what they symbolize. For example, no one understood why a book represented community support.

### Feature Description:
We will replace existing SVG icons with similar icons provided by E2A. We will not be developing additional icons.

- [x] Get icons from E2A
- [x] Put icons in place

**ICON FILES:** 
[CIP icons.docx](https://github.com/E2A/e2a-cip/files/2461067/CIP.icons.docx)
[TARP Icons_Noun Project.zip](https://github.com/E2A/e2a-cip/files/2461068/TARP.Icons_Noun.Project.zip)

**Comment by jayperryworks** [comment]
Note best practice icons are managed in the locale file. Change the file name there (`icon: [filename]`), then add to `spritemap.svg`

**Comment by sschafft** [comment]
- [ ] Get icons from E2A
- [ ] Put icons in place

**Comment by sschafft** [comment]
@ewilliams3794 - just flagging we need some icons for this.

**Comment by sschafft** [comment]
@jayperryworks - I've updated this with the icons.
